---
- hosts: all
  become: true
  become_user: root

  tasks:
    - name: Install required system packages using yum
      yum:
        name: 
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
          - python3
        state: present

    - name: Configuring Docker Repository
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        mode: 0644

    - name: Install docker-ce
      yum:
        name: docker-ce
        state: present
        
    - name: Starting and Enabling Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create springboot containers
      command: docker run -dit -p5000:5000 --name sh-cicd-test tmaxcqa/test:sh-cicd-test

#     - name: Pull springboot image
#       docker_image:
#         name: tmaxcqa/test:sh-cicd-test
#         source: pull
        
#     - name: Create springboot containers
#       docker_container:
#         name: sh-cicd-test
#         image: tmaxcqa/test:sh-cicd-test
#         exposed_ports:
#           - 5000
#         state: present
